### ISSUE TITLE
ReadOnly list changing if source is changed

### ISSUE THREAD

**Issue by joshidp** [mausch/ReadOnlyCollections#5]
Hi There,

I am using your lib. I found one issue. 

I have below code piece:

 ```
 static void Main(string[] args)
        {
            var values = new List<ValueClass>();

            values.Add(new ValueClass("100", 232.323M));

            var readOnly = values.AsReadOnlyList();

            values.Add(new ValueClass("101", 232.323M));

            if (readOnly.Count != 1)
            {
                throw new InvalidOperationException("Count should be 1");
            }
        }
 public sealed class ValueClass
    {
        public ValueClass(string sourceId, decimal value)
        {
            SourceId = sourceId;
            Value = value;
        }


        public string SourceId { get; private set; }
        public decimal Value { get; private set; }
    }

```

Now after running second add method of the list in main method 
i.e.  values.Add(new ValueClass("101", 232.323M));

Now the readOnly version also changes and it's count becomes as 2, but if it's a read only list why is it changing if the source is changing, it should be isolated from the source, isn't it?

Thanks!

**Comment by mausch** [comment]
This is by design. The `AsXXX()` methods only give you a readonly wrapper/view over an existing collection, so it's up to you to keep the underlying collection unmodified.

All the interface promises is that whoever gets an instance of it cannot change the collection. Anything else is out of its scope.

If you want to get a guaranteed readonly collection, use the `ToXXX()` methods, which make a copy of the collection so the underlying collection is never exposed.

**Comment by joshidp** [comment]
OK. got it.

One more query, just to clear my doubt.

If ToXXX() creates a new copy, will the process takes more memory? I tried running it and the memory usage remains same. My list has around 100k items and takes up around 200 MB, after making it readonly also process memory remains same. Is this expected, since it's a new copy?

Thanks!

**Comment by mausch** [comment]
ToXXX() copies only the references to the elements, not their contents, so it doesn't really increase memory usage by a lot.

**Comment by joshidp** [comment]
Thanks for confirming.
